// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxQ1j1zE1kplA8tgmlffrWr0ATPrHgcEA',
    appId: '1:1023060754466:android:5487f997a91d9dc25c4a7b',
    messagingSenderId: '1023060754466',
    projectId: 'nexordev-focus-planner',
    storageBucket: 'nexordev-focus-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmHuBTphJ2hnyt7D76FFHnezpCVEqNJQ4',
    appId: '1:1023060754466:ios:720fbc6ea8db2f435c4a7b',
    messagingSenderId: '1023060754466',
    projectId: 'nexordev-focus-planner',
    storageBucket: 'nexordev-focus-planner.firebasestorage.app',
    androidClientId: '1023060754466-lcsc56vhncnmrpe0grcsbk8uuftdq9n2.apps.googleusercontent.com',
    iosClientId: '1023060754466-rp37bduh2cm5bvfvg1fl43b971nkh398.apps.googleusercontent.com',
    iosBundleId: 'com.nexordev.focusplanner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMD4OzrOeCoRjQVmpKXtcRWdFjwROof3g',
    appId: '1:1023060754466:web:83b7b4cc4e2b2f495c4a7b',
    messagingSenderId: '1023060754466',
    projectId: 'nexordev-focus-planner',
    authDomain: 'nexordev-focus-planner.firebaseapp.com',
    storageBucket: 'nexordev-focus-planner.firebasestorage.app',
    measurementId: 'G-6X3GR7JFQ9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmHuBTphJ2hnyt7D76FFHnezpCVEqNJQ4',
    appId: '1:1023060754466:ios:720fbc6ea8db2f435c4a7b',
    messagingSenderId: '1023060754466',
    projectId: 'nexordev-focus-planner',
    storageBucket: 'nexordev-focus-planner.firebasestorage.app',
    androidClientId: '1023060754466-lcsc56vhncnmrpe0grcsbk8uuftdq9n2.apps.googleusercontent.com',
    iosClientId: '1023060754466-rp37bduh2cm5bvfvg1fl43b971nkh398.apps.googleusercontent.com',
    iosBundleId: 'com.nexordev.focusplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMD4OzrOeCoRjQVmpKXtcRWdFjwROof3g',
    appId: '1:1023060754466:web:ae954cf3a96c2dd65c4a7b',
    messagingSenderId: '1023060754466',
    projectId: 'nexordev-focus-planner',
    authDomain: 'nexordev-focus-planner.firebaseapp.com',
    storageBucket: 'nexordev-focus-planner.firebasestorage.app',
    measurementId: 'G-KR02FMQ8BB',
  );

}